framework:
    workflows:
        # Pour tes livres
        book_reading:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'readingStatus'
            supports:
                - App\Entity\Books
            initial_marking: to_read
            places:
                - to_read
                - reading
                - completed
            transitions:
                start_reading:
                    from: to_read
                    to: reading
                finish_reading:
                    from: reading
                    to: completed