<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCrudControllerconfigureResponseParametersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8yyrqQl.App\Controller\Admin\AdminCrudController::configureResponseParameters()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8yyrqQl.App\\Controller\\Admin\\AdminCrudController::configureResponseParameters()'] = ($container->privates['.service_locator.8yyrqQl'] ?? $container->load('get_ServiceLocator_8yyrqQlService'))->withContext('App\\Controller\\Admin\\AdminCrudController::configureResponseParameters()', $container);
    }
}
