<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookStatusControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BookStatusController' shared autowired service.
     *
     * @return \App\Controller\BookStatusController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BookStatusController.php';

        $container->services['App\\Controller\\BookStatusController'] = $instance = new \App\Controller\BookStatusController(($container->privates['workflow.registry'] ?? $container->load('getWorkflow_RegistryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\BookStatusController', $container));

        return $instance;
    }
}
