<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooks6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gUN0mzb.App\Entity\Books' shared service.
     *
     * @return \App\Entity\Books
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gUN0mzb": it needs an instance of "App\\Entity\\Books" but this type has been excluded in "config/services.yaml".');
    }
}
