<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookStatusControllerabandonReadingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gUN0mzb.App\Controller\BookStatusController::abandonReading()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gUN0mzb.App\\Controller\\BookStatusController::abandonReading()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.gUN0mzb.App\\Entity\\Books', NULL, 'Cannot autowire service ".service_locator.gUN0mzb": it needs an instance of "App\\Entity\\Books" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['privates', '.errored.2BrtWzg', NULL, 'Cannot determine controller argument for "App\\Controller\\BookStatusController::abandonReading()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
        ], [
            'book' => 'App\\Entity\\Books',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\BookStatusController::abandonReading()', $container);
    }
}
