<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_StateMachine_EventPublishingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.state_machine.event_publishing' shared service.
     *
     * @return \Symfony\Component\Workflow\Debug\TraceableWorkflow
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/WorkflowInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Debug/TraceableWorkflow.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Workflow.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/StateMachine.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Definition.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Transition.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Arc.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Metadata/MetadataStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Metadata/GetMetadataTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Metadata/InMemoryMetadataStore.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/MarkingStore/MarkingStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/MarkingStore/MethodMarkingStore.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['debug.state_machine.event_publishing'])) {
            return $container->privates['debug.state_machine.event_publishing'];
        }
        $b = new \Symfony\Component\Workflow\Arc('rejected', 1);

        $instance = new \Symfony\Component\Workflow\Debug\TraceableWorkflow(new \Symfony\Component\Workflow\StateMachine(new \Symfony\Component\Workflow\Definition(['draft', 'reviewed', 'published', 'rejected'], [new \Symfony\Component\Workflow\Transition('to_review', [new \Symfony\Component\Workflow\Arc('draft', 1)], [new \Symfony\Component\Workflow\Arc('reviewed', 1)]), new \Symfony\Component\Workflow\Transition('publish', [new \Symfony\Component\Workflow\Arc('reviewed', 1)], [new \Symfony\Component\Workflow\Arc('published', 1)]), new \Symfony\Component\Workflow\Transition('rejected', [new \Symfony\Component\Workflow\Arc('reviewed', 1)], [$b]), new \Symfony\Component\Workflow\Transition('rejected', [new \Symfony\Component\Workflow\Arc('draft', 1)], [$b])], ['draft'], new \Symfony\Component\Workflow\Metadata\InMemoryMetadataStore([], [], new \SplObjectStorage())), new \Symfony\Component\Workflow\MarkingStore\MethodMarkingStore(true, 'currentState'), $a, 'event_publishing', NULL), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)), NULL);

        if (isset($container->privates['debug.state_machine.event_publishing'])) {
            return $container->privates['debug.state_machine.event_publishing'];
        }

        return $container->privates['debug.state_machine.event_publishing'] = $instance;
    }
}
