<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_StateMachine_BookReadingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.state_machine.book_reading' shared service.
     *
     * @return \Symfony\Component\Workflow\Debug\TraceableWorkflow
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/WorkflowInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Debug/TraceableWorkflow.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Workflow.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/StateMachine.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Definition.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Transition.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Arc.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Metadata/MetadataStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Metadata/GetMetadataTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Metadata/InMemoryMetadataStore.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/MarkingStore/MarkingStoreInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/MarkingStore/MethodMarkingStore.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['debug.state_machine.book_reading'])) {
            return $container->privates['debug.state_machine.book_reading'];
        }

        $instance = new \Symfony\Component\Workflow\Debug\TraceableWorkflow(new \Symfony\Component\Workflow\StateMachine(new \Symfony\Component\Workflow\Definition(['to_read', 'reading', 'completed'], [new \Symfony\Component\Workflow\Transition('start_reading', [new \Symfony\Component\Workflow\Arc('to_read', 1)], [new \Symfony\Component\Workflow\Arc('reading', 1)]), new \Symfony\Component\Workflow\Transition('finish_reading', [new \Symfony\Component\Workflow\Arc('reading', 1)], [new \Symfony\Component\Workflow\Arc('completed', 1)])], ['to_read'], new \Symfony\Component\Workflow\Metadata\InMemoryMetadataStore([], [], new \SplObjectStorage())), new \Symfony\Component\Workflow\MarkingStore\MethodMarkingStore(true, 'readingStatus'), $a, 'book_reading', NULL), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)), NULL);

        if (isset($container->privates['debug.state_machine.book_reading'])) {
            return $container->privates['debug.state_machine.book_reading'];
        }

        return $container->privates['debug.state_machine.book_reading'] = $instance;
    }
}
