<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCrudControllerconfigureCrudService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eVx11yR.App\Controller\Admin\EventCrudController::configureCrud()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eVx11yR.App\\Controller\\Admin\\EventCrudController::configureCrud()'] = ($container->privates['.service_locator.eVx11yR'] ?? $container->load('get_ServiceLocator_EVx11yRService'))->withContext('App\\Controller\\Admin\\EventCrudController::configureCrud()', $container);
    }
}
