<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCrudControllerpublishService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QMWKcrM.App\Controller\Admin\EventCrudController::publish()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QMWKcrM.App\\Controller\\Admin\\EventCrudController::publish()'] = ($container->privates['.service_locator.QMWKcrM'] ?? $container->load('get_ServiceLocator_QMWKcrMService'))->withContext('App\\Controller\\Admin\\EventCrudController::publish()', $container);
    }
}
