<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerconfigureFiltersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vx1u6Ma.App\Controller\Admin\UserCrudController::configureFilters()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vx1u6Ma.App\\Controller\\Admin\\UserCrudController::configureFilters()'] = ($container->privates['.service_locator.vx1u6Ma'] ?? $container->load('get_ServiceLocator_Vx1u6MaService'))->withContext('App\\Controller\\Admin\\UserCrudController::configureFilters()', $container);
    }
}
