<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\UserCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\UserCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/UserCrudController.php';

        $instance = new \App\Controller\Admin\UserCrudController();

        if (isset($container->services['App\\Controller\\Admin\\UserCrudController'])) {
            return $container->services['App\\Controller\\Admin\\UserCrudController'];
        }

        $container->services['App\\Controller\\Admin\\UserCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.t0DHw4I'] ?? $container->load('get_ServiceLocator_T0DHw4IService'))->withContext('App\\Controller\\Admin\\UserCrudController', $container));

        return $instance;
    }
}
