<?php

namespace ContainerXbsxS44;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._ewVeMD.App\Controller\Admin\UserCrudController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._ewVeMD.App\\Controller\\Admin\\UserCrudController::index()'] = ($container->privates['.service_locator._ewVeMD'] ?? $container->load('get_ServiceLocator_EwVeMDService'))->withContext('App\\Controller\\Admin\\UserCrudController::index()', $container);
    }
}
