<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYEKRRxX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYEKRRxX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYEKRRxX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYEKRRxX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYEKRRxX\App_KernelDevDebugContainer([
    'container.build_hash' => 'YEKRRxX',
    'container.build_id' => '301fa1d5',
    'container.build_time' => 1775137870,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYEKRRxX');
