<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAnNvhQP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAnNvhQP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAnNvhQP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAnNvhQP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAnNvhQP\App_KernelDevDebugContainer([
    'container.build_hash' => 'AnNvhQP',
    'container.build_id' => 'b37d64d8',
    'container.build_time' => 1774309823,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAnNvhQP');
