<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbsxS44\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbsxS44/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXbsxS44.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXbsxS44\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXbsxS44\App_KernelDevDebugContainer([
    'container.build_hash' => 'XbsxS44',
    'container.build_id' => '6c820f79',
    'container.build_time' => 1774306088,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbsxS44');
