<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App_Entity_Event' => 0,
'App_Entity_Vote' => 1,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Event',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'type' => $o[2],
                    'speed' => $o[3],
                    'title' => $o[4],
                    'description' => $o[5],
                    'picture' => $o[6],
                    'vote' => $o[7],
                    'date_added' => $o[8],
                    'proposed_date' => $o[9],
                    'speaker_id_user' => $o[10],
                    'proposed_by_id_user' => $o[11],
                    'votes' => $o[12],
                    'currentState' => $o[13],
                    'dateAdded' => $o[14],
                    'proposedDate' => $o[15],
                    'speakerIdUser' => $o[16],
                    'speakerUsername' => $o[17],
                    'proposedByIdUser' => $o[18],
                    'proposedByUsername' => $o[19],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'type',
                'speed',
                'title',
                'description',
                'picture',
                'vote',
                'date_added',
                'proposed_date',
                'speaker_id_user',
                'proposed_by_id_user',
                'votes',
                'currentState',
                'dateAdded',
                'proposedDate',
                'speakerIdUser',
                'speakerUsername',
                'proposedByIdUser',
                'proposedByUsername',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
        clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
    ],
    null,
    [
        'Symfony\\Component\\Serializer\\Mapping\\ClassMetadata' => [
            'name' => [
                'App\\Entity\\Vote',
            ],
            'attributesMetadata' => [
                [
                    'id' => $o[1],
                    'user_id' => $o[2],
                    'event_id' => $o[3],
                    'userId' => $o[4],
                    'eventId' => $o[5],
                ],
            ],
        ],
        'Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata' => [
            'name' => [
                1 => 'id',
                'user_id',
                'event_id',
                'userId',
                'eventId',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
