<?php

namespace Container68Pmzfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9XrMDLi.App\Controller\BooksController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9XrMDLi.App\\Controller\\BooksController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.9XrMDLi.App\\Entity\\Books', NULL, 'Cannot autowire service ".service_locator.9XrMDLi": it needs an instance of "App\\Entity\\Books" but this type has been excluded in "config/services.yaml".'],
        ], [
            'book' => 'App\\Entity\\Books',
        ]))->withContext('App\\Controller\\BooksController::show()', $container);
    }
}
