<?php

namespace Container68Pmzfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.grHZGuJ.App\Controller\BooksController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.grHZGuJ.App\\Controller\\BooksController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'booksRepository' => ['privates', 'App\\Repository\\BooksRepository', 'getBooksRepositoryService', true],
        ], [
            'booksRepository' => 'App\\Repository\\BooksRepository',
        ]))->withContext('App\\Controller\\BooksController::index()', $container);
    }
}
