<?php

namespace Container68Pmzfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrudAutocompleteTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'EasyCorp\Bundle\EasyAdminBundle\Form\Type\CrudAutocompleteType' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Form\Type\CrudAutocompleteType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Form/Type/CrudAutocompleteType.php';

        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'])) {
            return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'];
        }

        $instance = new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\CrudAutocompleteType($a);

        if (isset($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'])) {
            return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'];
        }

        return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'] = $instance;
    }
}
