<?php

namespace ContainerEiKTGks;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MygkM6_.EasyCorp\Bundle\EasyAdminBundle\Config\Actions' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Config\Actions
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MygkM6_": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Config\\Actions" but no such service exists.');
    }
}
