<?php

namespace ContainerEiKTGks;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NSJYOmb.App\Controller\BooksController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NSJYOmb.App\\Controller\\BooksController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'workflows' => ['privates', 'workflow.registry', 'getWorkflow_RegistryService', true],
        ], [
            'entityManager' => '?',
            'workflows' => '?',
        ]))->withContext('App\\Controller\\BooksController::new()', $container);
    }
}
