<?php

namespace ContainerEiKTGks;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventCrudControllertoReviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QMWKcrM.App\Controller\Admin\EventCrudController::toReview()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.QMWKcrM'] ?? $container->load('get_ServiceLocator_QMWKcrMService'));

        if (isset($container->privates['.service_locator.QMWKcrM.App\\Controller\\Admin\\EventCrudController::toReview()'])) {
            return $container->privates['.service_locator.QMWKcrM.App\\Controller\\Admin\\EventCrudController::toReview()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\EventCrudController::toReview()', $container);

        if (isset($container->privates['.service_locator.QMWKcrM.App\\Controller\\Admin\\EventCrudController::toReview()'])) {
            return $container->privates['.service_locator.QMWKcrM.App\\Controller\\Admin\\EventCrudController::toReview()'];
        }

        return $container->privates['.service_locator.QMWKcrM.App\\Controller\\Admin\\EventCrudController::toReview()'] = $instance;
    }
}
