<?php

namespace ContainerEiKTGks;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllercreateNewFormBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5pLxdxQ.App\Controller\Admin\UserCrudController::createNewFormBuilder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5pLxdxQ.App\\Controller\\Admin\\UserCrudController::createNewFormBuilder()'] = ($container->privates['.service_locator.5pLxdxQ'] ?? $container->load('get_ServiceLocator_5pLxdxQService'))->withContext('App\\Controller\\Admin\\UserCrudController::createNewFormBuilder()', $container);
    }
}
