<?php

namespace ContainerEiKTGks;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkflow_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'workflow.registry' shared service.
     *
     * @return \Symfony\Component\Workflow\Registry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/Registry.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/SupportStrategy/WorkflowSupportStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/workflow/SupportStrategy/InstanceOfSupportStrategy.php';

        $instance = new \Symfony\Component\Workflow\Registry();

        if (isset($container->privates['workflow.registry'])) {
            return $container->privates['workflow.registry'];
        }

        $container->privates['workflow.registry'] = $instance;

        $instance->addWorkflow(($container->privates['debug.state_machine.event_publishing'] ?? $container->load('getDebug_StateMachine_EventPublishingService')), new \Symfony\Component\Workflow\SupportStrategy\InstanceOfSupportStrategy('App\\Entity\\Event'));
        $instance->addWorkflow(($container->privates['debug.state_machine.book_reading'] ?? $container->load('getDebug_StateMachine_BookReadingService')), new \Symfony\Component\Workflow\SupportStrategy\InstanceOfSupportStrategy('App\\Entity\\Books'));

        return $instance;
    }
}
